apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FpnSQ5OvFzcm4u8VN2t/wCJA,iv:gV1g2MB6IZ8JDC7zaGc2rFzswRaOSSPxaFgqnGhwqBE=,tag:Fa1ljoL2mBHLodRODt4PyA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:+eSKovbxUEIe91VNvIDH6W9aKIkeaTBcWCVqtoMbg7eIyrxcgg==,iv:qljIuCj68n7dffaTGvYmWMEBSNvaPEJBXLKi+PQArfc=,tag:tHzxyJibrphnYi7cq6L4lw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:UAfo2S5EFZbQtWtXTVaC,iv:bbuYA6cQb5N8jlP0N1vlYooas1OBKGU4vwjl5RZ9RFU=,tag:X+OVsQ6/3PdggJGrEyrLeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dERQd2tnc2x0dDZrdWdi
            UEJQaVk4cTMxLzZ1NGpRanBlOFBWT0J0N1RRCkxsZTdyNkgxOXZpRVdGSXVzY3VM
            U3g1L3BYd2pySDhvcUpVTzQ3RDBYUDAKLS0tIFJTcSsxSmgwZEJIaGRkSnVqTUhR
            WFNySlR2a3Ryd2NRWHZyL0dncjkyL28KN9jCwshgUOH+UssOfDjngUWu7o2s8KTy
            y6jcHESvv5Hz76l9hoRW6BhmLtXoknyxLIyExDshcS9lWhPMXXRcQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T12:28:31Z"
    mac: ENC[AES256_GCM,data:mHc1+jkkt0HmAmJx9kgxlX4f5oixF5B3kzOj8HWjy4WZIZJHgeHTs257IZL5S38RvG8gsnth3cFP6n2UM57xMMTgShuqY1j1PtzClPk4Wzr2iVaFQlKdpR7LyHL3LdfPaSfK8S/Ji380SC3YfolCSAE/kqGib7UwpZrnbQEss5k=,iv:+tmRM6VTpb0UqAJ8zX+p77EJNC2GYVxr7U40B2OEXao=,tag:FLPD1zGKVZfhXzXjaOpzMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
