apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uZuWbhM53H9uiluKeqMODaDe,iv:+ftQG9zI9CwTkL4QNHHLNBAAZ3L1TDJ2Aa8W4Imkgvg=,tag:SkMLgCYJwlm+xw2XYUPsgA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ttQIzV9nFYIJlyKczq5vHvmN9ONR02ZHI/cNYTSgpOcJReLDhw==,iv:xy8UxwIzmRdfUudw/7VQpp37QWMOhy7o6M+Q7+4jeoA=,tag:d6pKT3f0uyR2PZ0NztDEyg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:zoJFIHLpAIrVB4TxppaK,iv:tYualXkU0vC4oOz+1Jrp0cE30cCdAj2yQdDyZzajQOI=,tag:pZd/3zn5H1dH7HAWCl2g1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU0FNQ0ExcVlnS04wS2lW
            UXhZdmZjZWRGbUsvMHZEQWZ5MS9KTlNpclJVCjJ2aXhnME9QRjJ1Qm9xdndmSkNJ
            RUdXZHZRajFxTlk2dEQyVkk3eEdOeUkKLS0tIGVybUdYMnMzTFkvYUZBeEtKRjJx
            VGJaQXNHVWY1aXBiZGcxNXhZOGljTjAKCuRwLxUtd/94/Ix5H9RNZKt3qIhSRu3S
            cwRUV8bs5Yxkuc6rkD/4894ipCwL2TUhoayWGhbWgmtYbYoLV1VfSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:01:41Z"
    mac: ENC[AES256_GCM,data:clhh4ZQzlUrnbVRNYoA9fK7Wsl1oreWkYd4hij6dHlD5EPBNcn92WO/Vw7AJstgBkll9HdOFZEHBL8JYer03W9TvXwkyg0jVh7gCpkgip/cZpDh77gdIwxI1eXs1YvA+gSy1laBn85YUzv4sQGUhI3hGB+hHBG9Q1kWDnNK0oII=,iv:DftnpwwBkNLqIIVjgudauaQYMlSXLRd4FsUd3Lo1WNA=,tag:0e2q51LtmW6jihNUPXC9oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
