apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yEl5v10wAabpflh2bItPfDKc,iv:3qWeczGa2Sjaq9DtNiiIzL6X87660aXLcZ90V12bEUk=,tag:/GVpJSUgQ33Y4LxwJqhXPg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:l8JOXoEZKWlRDGR0xhxcMoxPkKoBsw5v7hutkIFR4X/qYfLQlw==,iv:6egFLrcYjv8OnF2m2adUi6oYMA6a4Cj4irSa6mmJN+c=,tag:JH/YSu97HnMzanrsjx2NZw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:I5aRU9LKHjgFStB8eESM,iv:Q77FgpxJrP2a52HEGrcRXImA8NPqDeYcBUvJWKUo4qs=,tag:zKhhNq3bdm5mgjzR0IFg4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVM0ZFcjQvbVFVWkRWcTVC
            QnlHb3VYdEJKdmk5a1V5ekFqZnRHZFVmZlhnCitvWTB4L0NwRUdwdmVadzlqTmht
            NnlCRmZRVmZocWtuV3ZHeVJHSkFUMW8KLS0tIDdyYTM2Y2tXTjVmaEo3Vk1pNTQ5
            QXFmeFQ3OE5pR3JwOW5sTkNhN0NjUzQKqHXhFrH3V9TlQT5bYcKeDuMEC65iPU09
            jdBmDaElMnZYUm8NNPupuQmb5fl+7nBOPeBcd6vyq1f2jAHEgkiGXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T09:36:54Z"
    mac: ENC[AES256_GCM,data:ZiP5fo7Y1T+MvcfCAujEcXE1LoK/7WcIFitGXjlyKythl/jsFWOG2qzc9YIt2PVoMeFHO9eYhfph5+UWbUkFKTnygDV98N0APqGZ2BUXPau+5v+wp+YKP8Og0WGvaKd6gA+JNrJaN6JDE1bp2MfkuB5p0O9Si6kMJdGm+Ukn120=,iv:4VwtMMZssZ8t4BPqEwbxXfIMmlv0+NhcSt4BF401ggA=,tag:grDbGpzqi1ct7IhRPj8wgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
