{
        "data": "ENC[AES256_GCM,data:+XGZ6AO8r6gmspG1QBxLpie+ssQOic/Ra9tFpGD+/Yr1TOiuWpqHTlSYZ5HNsOXgm1XZP0fj2Dp76lDBM6p2I39ltuQU/TGZoykOn3/J0UlV2KT6ghIlkf4B5w8FVkBJWO8u8sQmCIsSoiKO0Z7HaArzDDNa2XjqCXkARIcSzAHx40AVugwvvRUFXG2ZN86eYzOs95nm3CdOGqoTXQA=,iv:/81VmAeHL8Mcr2crpX+OcfhKdjU3pR6H5ETLZli7iDE=,tag:PDuxH8Yl2VuErQ4AWxEj+w==,type:str]",
        "sops": {
                "kms": null,
                "gcp_kms": null,
                "azure_kv": null,
                "hc_vault": null,
                "age": [
                        {
                                "recipient": "age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w",
                                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV05qMm5ITHIzUmtwUTc5\nTWJTeG5ISEJUeDYrbmpqTWdPRHJLR2Y5Z1hVCkNBZENkbG1aUUxYTzJDQUVRbHBu\nQ3BUUzlMYk5vNDZyY0h6ZzFBYkJSVkEKLS0tIEFSV1huR1dPdmE5dXFIeXZOdXRH\nT3djMjBaYkp5R1VlelZRRHlFRlFJVWcK7sYl7bKlLhNW2zBA3SsXXhv9wWuZmhsO\nlf3LWvkSEjgtImUI4Pq8KC6odwr83Vat/4SsARcB/wHBr3nLp6prLA==\n-----END AGE ENCRYPTED FILE-----\n"
                        }
                ],
                "lastmodified": "2022-12-25T11:21:02Z",
                "mac": "ENC[AES256_GCM,data:CBNf6MeYMTWEcEhjahIto0Pn4N/+CZmw1spsWvTIG4UUoZhTRUgtFebDZpyT6X5lrwUU2pMtkx9/UbOtdhjeMXckiKTcAn4nOF8vElgCxWKy2VliBzYYscLwJjf2mDOIEzdp+jl/HgwLd3GhmJbhsDTP2vCqnLv5g4s4RjiJPVg=,iv:cKcrZx0cICCzZzn7Ixa4de6Q7w6kBeDGYg1ceWff67Q=,tag:TOMwHWSNvtUWHQBHuaWQrg==,type:str]",
                "pgp": null,
                "unencrypted_suffix": "_unencrypted",
                "version": "3.7.3"
        }
}
