{
	"data": "ENC[AES256_GCM,data:EEmaXzqb/+iitDf0BTkUKUJIcGNuMjYm5J7UzWz/1Pm7+RKkbtSwDzt0YxDSVJXvcy142nG5Y5PcvNF1J5YX0eLqeOO12Q2PqHwZD4SFtDEjmCP/ZbQyPCyMAvr/aE4Xu+po3u7C++5Niw0P6X3YfM7BRk4Y/gvAsXp5vdUg6gHV3FP4ueS1zsJLU/7NCdPtcMScJNt1Emmsu9pRMO0sHQ6nc+7CPOh7de3kyZ8uPlowUqi56j02HrlivfVWwWOx6dzDxHzBZFiDiei9hx159INQSO/2aAK9fejFV+Ip660mOqTFT8cSvn9JJEk/1NVCy1JtPBeS0TXWfYABUT7JOM2PVjsfDcAAdS/8WmcLPdryHZFtsoFcGItz2Gqnm0an7ighorVxng7G1bplAxMnQHXW27Ye4KzYnLzNyOYK83pmV1IPJld/VbiW8NO/r8n28g++H6ojw70cbBJyxjrvP8Lcub4kxByjbTJ838KoPh7kFn+U3pLMcBZVYkA535DZNx5eRxoZ3X80abA4pnwH2ZfoSUPQX5toPbVLP95e4RiFKOzYdO7f3JA1o4OIV9TPXymxcWfgvkOzxbLTU+vcy5l5L6HqGt3B8G3QYRDdy5IvSeIQ,iv:wjgYnzzriY/gvOLg7Xi6OrFL18/IcylPm+dm6qhgfG8=,tag:Qw1ozdRBN/CuPyiYgbxiAg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOUpiVmVvZ2pES1JBZDdT\ncDJTMFFqc1B0clg4Rkt4L0ZvL0tjTFl3YkJRCnhTTTl1eitxamhBcThJWU9GS1Zn\ndTdsdnRsWHNyUGhBQUlaNTRxMjNpeHcKLS0tIDEybzhUWTVzWU9VVXpjWUl0eUVj\nalJlQ2pHa1oxM0oyNEpVK2JxcTIrYWcKQjgQQqgZfaARWQSB5XSViV52JIZITjov\nmDYZA7pmbmZDt3+t8q/UNE3fWIBxaGzGC2Ej5BzjoYZPrrnTpON1pQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-12-25T11:23:43Z",
		"mac": "ENC[AES256_GCM,data:xQjwRv4mWE3ghiWvx1uhWaB8Fu1s45piGzD2VSpfb+9OYDYQXumDG67u2B/AogWFHjhz0GSs6UXcptfrrER44E7XCLJ3hOXd6fs8U59IQMRdb1uSJBtOCmoB49CXC9JE5KqA9rUIcFBmDzpToAYLxpq0Vta5nGKk+STqEz+UsAc=,iv:cwqy+79LztOx6WrQl6oiJW8ioMBoa77cVjDMfQx6mqM=,tag:zq9GlCqVwFuoU9cuOjViBA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}