---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-nfs
spec:
  capacity:
    storage: 20Gi
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-downloads-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.178.241
    path: /mnt/p/Downloads
  mountOptions: ["nfsvers=4", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-nfs
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-downloads-nfs
  resources:
    requests:
      storage: 20Gi
