---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-truenas-nfs
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: democratic-csi-truenas-nfs-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: democratic-csi-truenas
