---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: truenas-nfs
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"

    storageClasses:
      - name: truenas-nfs
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          # for block-based storage can be ext3, ext4, xfs
          # for nfs should be nfs
          "csi.storage.k8s.io/fstype": nfs

        mountOptions:
          - noatime
          - nfsvers=4
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    volumeSnapshotClasses:
      - name: truenas-nfs
        parameters:
      # if true, snapshots will be created with zfs send/receive
        detachedSnapshots: "true"
        secrets:
          snapshotter-secret:

    driver:
      config:
        driver: freenas-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: ${TRUENAS_STORAGE_IP}
          port: 80
          # allowInsecure: true
          apiVersion: 2
        sshConnection:
          host: ${TRUENAS_STORAGE_IP}
          port: 22

        zfs:
          cli:
            sudoEnabled: true

          datasetProperties:
            "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"

          datasetParentName: s/k3s/nfs/vol
          detachedSnapshotsDatasetParentName: s/k3s/nfs/snap
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 568
          datasetPermissionsGroup: 568

        nfs:
          shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          shareHost: ${TRUENAS_STORAGE_IP}
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: apps
          shareMaprootGroup: apps
          shareMapallUser: ""
          shareMapallGroup: ""
  valuesFrom:
    - targetPath: driver.config.httpConnection.apiKey
      kind: Secret
      name: democratic-csi-truenas-nfs-secret
      valuesKey: api_key
    - targetPath: driver.config.httpConnection.username
      kind: Secret
      name: democratic-csi-truenas-nfs-secret
      valuesKey: api_user
    - targetPath: driver.config.sshConnection.username
      kind: Secret
      name: democratic-csi-truenas-nfs-secret
      valuesKey: ssh_user
    - targetPath: driver.config.sshConnection.privateKey
      kind: Secret
      name: democratic-csi-truenas-nfs-secret
      valuesKey: ssh_key
