---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: emqx
  namespace: default
spec:
  sourcePVC: emqx-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: emqx-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: freenas-nfs-csi
    storageClassName: freenas-nfs-csi
    retain:
      daily: 10
      within: 3d
