---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: echo-server
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: testing
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
  data:
    - secretKey: icon
      remoteRef:
        key: testing
        property: icon
