---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:

    upgradeCRDs: false

    image:
      repository: velero/velero
      digest: sha256:322dc1956d9b754b5baa626b819fd6f06096bcd70c218621c8de8b1ee828bf66
    kubectl:
      image:
        repository: ghcr.io/onedr0p/kubernetes-kubectl
        digest: sha256:6ee3353da3495bc99d73af29a4495bb95570e31e71579cfce719c4123882723d
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.4.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    defaultVolumesToFsBackup: true
    deployNodeAgent: true

    credentials:
      existingSecret: velero-secret

    configuration:
      provider: aws
      backupStorageLocation:
        name: backblaze
        provider: aws
        bucket: mdegouw-velero-test
        default: true
        prefix: velero
        config:
          region: us-west-004
          s3ForcePathStyle: true
          s3Url: https://s3.us-west-004.backblazeb2.com
