---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freenas-nfs
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"

    storageClasses:
      - name: freenas-nfs-csi
        defaultClass: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs

        mountOptions:
          - noatime
          - nfsvers=4
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    volumeSnapshotClasses:
      - name: freenas-iscsi-csi
        parameters:
      # if true, snapshots will be created with zfs send/receive
        detachedSnapshots: "false"
        secrets:
          snapshotter-secret:

    driver:
      config:
        driver: freenas-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: 192.168.178.241
          port: 80
          allowInsecure: true
          apiVersion: 2
        sshConnection:
          host: 192.168.178.241
          port: 22
        zfs:
          # Make sure to use the storage pool that was created previously
          datasetParentName: p/k8s/nfs/vol
          detachedSnapshotsDatasetParentName: p/k8s/nfs/snap
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 192.168.178.241
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""
  valuesFrom:
    - targetPath: driver.config.httpConnection.apiKey
      kind: Secret
      name: democratic-csi-freenas-nfs-secret
      valuesKey: api_key
    - targetPath: driver.config.httpConnection.username
      kind: Secret
      name: democratic-csi-freenas-nfs-secret
      valuesKey: api_user
    - targetPath: driver.config.sshConnection.username
      kind: Secret
      name: democratic-csi-freenas-nfs-secret
      valuesKey: ssh_user
    - targetPath: driver.config.sshConnection.password
      kind: Secret
      name: democratic-csi-freenas-nfs-secret
      valuesKey: ssh_password
