kind: ENC[AES256_GCM,data:WC4brFOp,iv:mno+LarAbTmxNje+eNSXEw0SAVudQSfFamPQKG2TZUU=,tag:ObeT9ruemYBAOkZWbzfuGg==,type:str]
ansible_user: ENC[AES256_GCM,data:2B9ZPfuw4A==,iv:NJ2ixMNNXZqNVmfjXFKlp5yQQ/CAfvly5N4ae9NSSR4=,tag:Z6NHcvDczrxmuLwZMG8fcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTUpJamFzZjd0ZEVta1ZH
            NE5ReFh6eHp0bXV3K21QajZMY2o1eGxJbWpvCm9tdDUyd0V2anBBT0dxenU1TEQw
            OHZxREw5anpkVEVERm9CT3Y2N2tuekkKLS0tIGd3dzRvT0hZY2E1OGlmaGZmWkQv
            ZmY5N3RxUTBLTXhhTTdOVnMvWEdMUkEKnePNDhnVoxRo+wjGLaLF2FgfYnFGIF+N
            u9iRe6SyVSzxSlt3PUBtQGzXeXMSon3B1XG6qac2uylsTYQ5hWRDtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T12:30:50Z"
    mac: ENC[AES256_GCM,data:AxAynEOT/aTcoF90vBPX3DdBhtnLLqTlCHP9h9bKP6vGuO4XN1hNraRLH5QwWuSU1xncQGip4geLGYkpY8mv2uOGsmbZg8AoqSKxrTl/wI5inTnS/a9lkdv5oJzUSwrrPaEsydv/YxP1aFX2/QSGfW/WQ5OXrMyfh+juHvAkGb0=,iv:1hsFe5Opdr2XHPK3TfRZFMNidIwGA0CxYCkGyy/ZFBY=,tag:kAuwo/0lpHuSh34Xi24C0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
