kind: ENC[AES256_GCM,data:BsAWZ9yt,iv:vg3H2BNni96SDBqbDi3xUxx+ludOnRs1wFOEnUeuWyg=,tag:1003bCrpGu89EbnOXFT/jA==,type:str]
ansible_user: ENC[AES256_GCM,data:i5oJepZshw==,iv:ajXlz7Y6YCpG4E6TIohTaIUulVTNPypaPw7iWhwh3rI=,tag:eQqLZvapeFbmX1T8UCLLYA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:x2iVSLspCDjF,iv:m/aaj+dwZ8zJP9hmhjWQEBWcwlVEnChmhGbRDrV9QB4=,tag:uecWKNT8vZv/+6+UVDdQBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMGpINEd6QW8rcFpUMkJh
            SkVlblRTaXFmSDVlZVVNSTlVS0VESGhkTUFVCmV6TjMyeUNGZVVsaElQTDBzb2lv
            NTVhYWFuV2JMK2hZSkUxRnBmTXk4T0UKLS0tIDc2ek9Od1p0eFpmSytxb3RtbCtL
            R1padEZhblJuVnBLVWU1ZitKdEJidW8KUhEqahf5MPNnU6aEPMEl3LkV3qAAMr6L
            TfKN/3oKt8zfbHlANxRmfsatDhVV+FqyQ3mH5gX/KICHAZQBa+alLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T09:36:54Z"
    mac: ENC[AES256_GCM,data:vDdxm0KXLfCKgKrmtWAut28wo2gvPE4ODSIfZw59ip1rbt6xU8/YMnxU0Tb/3yt80O3naScYnM/N4mB9LPVyUjgvJOVs1EVY6YNnXy4jjgIFkffkZJpEuSR8z87DGntE3xrKuTeoDFYVlSzdSPBZIeyA1zT93rbT7dvd/xYlU48=,iv:h3JbRLViiqMwB6/5oSeGo4Dy6uvurXRIkFxQ2QI1DL0=,tag:/V8czw2NIiYxJZqm0hk8Hw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
