ansible_become_pass: ENC[AES256_GCM,data:76qxCj+58Ib9dH+vuw==,iv:+LgetgVQOMULvu5ZVbwbKZLxpZlWkkjOtoTuI/QEXzM=,tag:qdDmZcOqpxdlEFhAAa0mhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqnf07rzxt8jkwzqyx84t4ag9az3n35hw4m298v6s56d5mf509lqrpcflj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZVZhSFhyWlNGT3daM3JL
            ci82Qm9URHppMjhGaU16bmJhRFhLTFk5UlNFCnlUcjlEeGR3UTlzOWNDKytLTjJG
            bWF2Ujk5ZERrYXVvQittSUo1NHdISDgKLS0tIFhVV1FydURtaWJkMzJaTmticXI4
            MC9KVTFENGsrcnA4MTg5QUZ6NzZFSHcK2h/OsR0kje21NMppXH3jwHirqJHOzugF
            ZSr3g3reeDuccgBnXhkXYmhBsSuxCiyeQefZSjyPzSevtrH/hT+XbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T17:40:20Z"
    mac: ENC[AES256_GCM,data:Lqm9rWGMn8aAYQpAig3BXUJE1xUy3AeDSX6Hh5vngtjh0IwLm9GeJVDT7MS3wCEtdMfoUFmXs2CSbL3YUctj2dnmNFVkcNunZcTKWPgf2pjrww/dc/MuVg0OL08KYWl+EU+P1IqxJ4pUuDDZ+e/RM0yUVXKcWYVu3nbiCqxv6S0=,iv:jaFTwtjaQOgY/dSPVbNjeNtEXZIV4NJPEbCvgw6K+7M=,tag:HoqmfrEEG5wEFhLW5ToWuw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
