ansible_become_pass: ENC[AES256_GCM,data:ryBMsr4yLqtTIszSGw==,iv:kriBxLqry3/0gvL7d+c3yO4iniFR1G83H2xrMvtCnmc=,tag:FOXuNqC0VmLnShv9suKAdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqnf07rzxt8jkwzqyx84t4ag9az3n35hw4m298v6s56d5mf509lqrpcflj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbmsxbU83TnZDemZsbWRz
            aHowczg2Zis1bzBxVGF5ZW1Oa0pVeGs3bGpJCm90RUtBYjhLN054L2llVmxMMGVF
            RDVKWU14b1BsWGpSd25QOXBGTmxuNDAKLS0tIDFiWVU2czBicDRTcDlSVE5md1NP
            RWNlMzVZT1VQN2ZNWlhYRGd1Rmo2QWMKw3oVs1L/zsTAhWEw3sSidpU5aEx7M3sJ
            f4Y4ZZ+qSMF56Cl+Q8dFBoNnd2Mg0r6y2NivvXHREe8EdFBnpaYdsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T17:40:20Z"
    mac: ENC[AES256_GCM,data:uwjUAbhh8/zubiYeaTrERyUMbV3yhwk+5Qq40akGjnBUGRqU/ZMVmPUBwX233mdqfoPZi2gEkgDT7riA15NQeNoMHl8NuMGfJ80NN/WC7XcooskB1N+bDcfKgYB3goDGF9leGliuRt4b/iVLpbBRHAWActZJFt5gOeUui6WVggo=,iv:2V2rx5EQQlo1ocnlq5kKLu/jGOtJy2GjjWlrQbD2fpo=,tag:w/7G/30RjA6bZAZDi+rhmQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
