kind: ENC[AES256_GCM,data:IGlVs77M,iv:q5LkVvTxZz31mfbh1tZrFJPbd7I8eiXDcsdV8LqmUis=,tag:X4sT0Eo3htHEQweoor+v8w==,type:str]
ansible_user: ENC[AES256_GCM,data:+N5GZBrBEQ==,iv:gDT5c2ZkOkIkSvxJwVxW77BoTE6smUpQ02YQQCFeaNw=,tag:R5VdzcOKeDdkg9yA5di5fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZXdtWUFNTXgvbGM2bzcx
            S0pYYit0a2dqdUM5aDZ6RUthMjh1OEpraERzCnBPclBOMTBQQTlVS0NnbG45QWRK
            Q2JacjFNRjluQU55L1JWQXprQkJPakEKLS0tIE1LOGZQMXk5UzdMVkhIWFhsV2xJ
            anBuVDVFNWRyYzYzekFrQTgzYjEySTgK+atHZu8eUzesD8aWEAlMZZk+ONq60gIF
            Y8AYYFDiexOH6jiQFtmov4vTbBn0kAnN2BpUz7/0tyyc7aBHoNdU9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T12:30:53Z"
    mac: ENC[AES256_GCM,data:4+fwiWsvhPUdNg+NpC5RlOJ87E9vn5hcwsPl4noDr/iJh58L9yvhofUUH9ym1bB20udF7gNcarXtbW0Ie4+eoLf3wKgLcnFm7cDwRhIYJUrc6z20OMCH9CYh0Kani8C/cyyW7f+rW3Rs7CueSJcwN4PCVR7i/dQNmrBnzyA+/0g=,iv:XEOD+2Hm/Srw7EKKS3f6//f/OsRm7j3K69u9fZeId90=,tag:/RLQHb4/OtImLOe/n4j76w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
