kind: ENC[AES256_GCM,data:IGlVs77M,iv:q5LkVvTxZz31mfbh1tZrFJPbd7I8eiXDcsdV8LqmUis=,tag:X4sT0Eo3htHEQweoor+v8w==,type:str]
ansible_user: ENC[AES256_GCM,data:+N5GZBrBEQ==,iv:gDT5c2ZkOkIkSvxJwVxW77BoTE6smUpQ02YQQCFeaNw=,tag:R5VdzcOKeDdkg9yA5di5fA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ItEJvNqKZ/QR,iv:UlJGTRaD2Exr055rK9uu28yCOpUNc/tnZ79Tf5xu1Hc=,tag:getFkxkWsIBZcttsI7CxXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZXdtWUFNTXgvbGM2bzcx
            S0pYYit0a2dqdUM5aDZ6RUthMjh1OEpraERzCnBPclBOMTBQQTlVS0NnbG45QWRK
            Q2JacjFNRjluQU55L1JWQXprQkJPakEKLS0tIE1LOGZQMXk5UzdMVkhIWFhsV2xJ
            anBuVDVFNWRyYzYzekFrQTgzYjEySTgK+atHZu8eUzesD8aWEAlMZZk+ONq60gIF
            Y8AYYFDiexOH6jiQFtmov4vTbBn0kAnN2BpUz7/0tyyc7aBHoNdU9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T12:28:31Z"
    mac: ENC[AES256_GCM,data:pgSrMoVLzFRRxFHUOr6KCHjvNjIGHPPuYPvObKh9edlOMiX9y+GknV/BBjZe3ssrQwt3lB7Go32Py9p9i7UHf7XeV5N7PZxocg9Sq5u4vnlLehF2beWYUuQC7E4Uf7j6O9iYgf7Ne54LBFOz7IjPAGR95jpkEAdBWvpJZ0JYU6g=,iv:IWjUhCExqiG8V2Cz0J1RA7LpZg0IqpUifA1vDvqV364=,tag:ZXjpi21wasQMWqO02gG3sw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
