ansible_become_pass: ENC[AES256_GCM,data:5cxQ5dkWWXbfH76Ddw==,iv:Ezpk4bJvkTAzIj0VXU+EHI8s1xTEDBLwMUSr4nLKTvI=,tag:PBGJiMkTDn6PmfgFVf921w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqnf07rzxt8jkwzqyx84t4ag9az3n35hw4m298v6s56d5mf509lqrpcflj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1V3lsN0ZHNFVIOUpaZ1pw
            aGZ0SkVIY1FKOFM1aXpnS1llZ2hoZjNYMzMwClZDaCtITHc0K2ZOaFJWMjQza1lG
            dEdIMVlKdDNJaVl2NHZWRHVPSEVhUXcKLS0tIHJ5L1Vic1ZQd2JESFg1bnVaS0pi
            VTdNemVCOHRyamhibFR5aUExVmFjTmMKBaRK6ElmL4o7cZYXooNaZrUX8wBYTr5V
            ev8QrPym4+Mo8FpVmspnStbj7/T2oXLu+v4IiE9pTR2aBIUPeyYzAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T20:33:31Z"
    mac: ENC[AES256_GCM,data:W+ZpBoTDllKW1tMMADJXNdi3hLBQFMMeXn8Ok7RG7jx/Bi9lSCIP4zZqP5ShEFBBCWQ1ptXrn2jqp9QrMobyk8sM2BHDLzaJ9LolRr3bJDZUM/NZlJwMmXcppuh/3IuwLkuzkXX1NNoKXXWOdUlm6u0GzJkPQ6vC7VjBiBSYcMo=,iv:47grICjWIaoLgT3bd4rXDVLw9OFt1jnYBPHTj3+ObEc=,tag:s9ZOgpo8465FmCKPZwdbEA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
