kind: ENC[AES256_GCM,data:LOhXmTil,iv:acKVETxAhSDBv/YNg+7oDgf9pCTdWKa13v1JVSHGyhQ=,tag:PhkdoKpMcZeq2jAXsgBd0A==,type:str]
ansible_user: ENC[AES256_GCM,data:hIIeOLQ0qA==,iv:k5iZxdpHqmzqvtwLvGiP+zD2+KtO13WZAy3GBNE3BXk=,tag:FSPjmloQPqvUDcp58D5LdA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GsAhf3171UpW,iv:rrWmLbhPHWQoxfhWH90OcURzZmpsNealkBrYNazCPDU=,tag:lHwn4y0NJ3yJv2/KcQZzdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdnluNXhhaVJsSW9PT0RW
            MU83Sm5xVDh0cW5hMi9UWWR3Tzh2eFk1UG5FCmpHOUtyVk13eXNGZ1FKVnRIdC9F
            R2FhK3pZalA0L1NmL01tNm5KUGJxdDQKLS0tIEFiOU5VL3pPd2VXa050ZFJ5NDlP
            RVdIVUVWV0hUN055OThtVGpDNGdQcTAKAQ/KASxMjsDickbRg2LWQay+vnpylV9r
            6j3DeTiS8EEkqP4TIrwofgDT530bEeSBRMRn+g1HRTTXwKYPynwF8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:01:41Z"
    mac: ENC[AES256_GCM,data:t1BuhBZdxVMm1nS5Cr7nnnJWqchmYW0M6OVMwqUvxxh/mKCu2bdOF967T2dfSOcWFTPrXWqoOsI6SNqqOV+uhZIr9AVDMJtgKjGMMGMKMnZVY//XOPjlygkh1vJFeXPN6uh7MvIzq2sDRGLhdRoZHyaz9jQBUQAFByBEWCP7+s8=,iv:q++8tz05+HiEM5Gqjn4n7TpVNtEmPOyACubT06RVDVg=,tag:WkxucGmZekxgFIsCSvVAWw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
