apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:a+5cUFC9UoMciIoEz8yQGjCCp9hvnkmXIKA8uHXhrNVTZlSa3AA74Q==,iv:zL5QkIo+g08J2zqD2ISuKW7jln3aPH6h3D6omAzCa9U=,tag:JgPldPfd4zy5lkTYZ8iiew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcUdIZUJhYUZ6bTQ0R2xJ
            YnB0OXhHSzE3ZGhpOFEvSzA5aGdqaTJJdWxrCm5CaU5FbzhidDF4aDFRcE45cGNF
            VzYyNE5jVFhhNksxa1JHZmNMUStMS28KLS0tIG5WYkRxRkE1dXp2ZmU4dkxObDA3
            VldlV2NSdy9iNlJRdFVRaEdhMkhUTlEKREHcwozHfLkwT7Y11wuy3UDMQGpQYeyg
            TfklxheyrmzDHnGRMUY9EKxpgpjrUy3wJ6mS7x/ZTVWeRXMxgpXAzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T09:36:54Z"
    mac: ENC[AES256_GCM,data:81K1XtpAZG7XKyJg8Vnpabjj+O2ebXr/kpUK4af+vfcjLQIl13ECMVWcge6dkrdx1L2fQ4frxNvNlsg462IORJoz47Lhb6Wmxl3FRY5ZU63iPy67VI3uEm8aqMVDu8nvOljDKr0dBycXQf6pbli9T8LrYXPjUyZ64MVYZ5bOC4U=,iv:AYYQ5BxJKSchNYSyIriGx1dElLMh73bB4zbui5t3RMs=,tag:ocLkeil3e/oLnv2Du4ijFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
