apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:aAFW2voeUlZGi+db5qgru3N/CaOceOJcskbYlrN+cDPXcYBSJwe59g==,iv:+e8gak14a4C/cT1GgChQZroeccYx851qw4CkPbX08PE=,tag:ABX29Bm+x7X8EsBvbeNQNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdVZqRGszMnE1T3VjTTB5
            MW5wWkpSRjNkNG1WNWpzL1NZMGVTYWtxam40Ck16djgxTkNjNlVVbU5HR0xUUG93
            UnFWd3RGUGxYVjFFZEJUdmRiT25NTFUKLS0tIFE3Szk0azFvdWtBT3R6dGdEUHFp
            TEY5LzVaK1ZJelBEWlFpRWpPZFh2S2MKOqPUBmueyT9uupdC1puQyHfhc/bgUV6m
            ZDAf26xKCmgvwQTsfm5G4QlHOliqflgqti3hEr9CJ+tIvjYkkhX+NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:01:41Z"
    mac: ENC[AES256_GCM,data:P4vXQzFMAnYhFJBj6UpjdWaJXwCWLPyPoXkGeoQNSVtKeGQjuTcJe5eBAa/PwW8vRBRMI2wbGK2QYqq+0XtW+FWpVfOUWgXzuk2pKo6e6L/JRVmvBjl9+jwmffZ8tD/Fj6dcLEiqq5KGb4W0x4IROxarY2e71vLbsQe7U5BVEh8=,iv:RSFXlI3YQcEsHaaWLXI6kmMjdfafUgWPWkx9BoH/Y9o=,tag:nSjkG5Cb+XDYVPFyP4ScRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
