apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:geqt/F2v+QTgQ5bLv+f7UYwb/PenGif47VxvCoF+I74a7asMtbeFhQ==,iv:nd984JVGOf3tA3DBqiZ5RQc598g/Sb/dwrve2wsPmUo=,tag:8pRFgA9adW5kTFLSMeIMSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VklHSVJMQzE3bjN5YWIx
            dStjM3pBKzkxMVZ6YmNxWVQ0bVpraFRETTJNClJiTXljMStSRk1hZ29CL3Rmd1Bj
            TnA4S2xwMzNOZ1FVZnNZazhVZGszekkKLS0tIHBNUUM2Z0hmMjdJNzdicm1VOGxX
            eHRCOEg3eWlydnZVdWEwODV2TkVWelUKzNiBYuMC+qRegKqVAXtHc6T5E+uUcaWs
            WZd4TIf5ataNFhizGpgtUtaBdXzHJ4//GTfS3qG7TZ3eI/U6fEoPcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T12:28:31Z"
    mac: ENC[AES256_GCM,data:X1fUEnHB9jGNPholRKVYcnElTQsYCr8myPVlmPGNI2k6qR4L83dsVHEIv83chCpBKDlrpNxV9ZkR0XzXpc8laKW6SPUIE1iKl2UbPuihjhG/nlcygUsVWtJfmndpx4CzdUaZYOQLhRYlQpo+YC+rMBge64M7HXfhMVsALjUl1lQ=,iv:gfZBBk5muEJFPamcWpO0BxL8j9w5ZeEwdTgsmZddP8g=,tag:82e6NksZ8mxnY1oEw7Z/UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
