---
kubernetes:
  children:
    master:
      hosts:
        k3s-master01:
          ansible_host: 10.100.1.21
        k3s-master02:
          ansible_host: 10.100.1.22
        k3s-master03:
          ansible_host: 10.100.1.23
