---
kubernetes:
  children:
    master:
      hosts:
        k3s-master01:
          ansible_host: 192.168.178.161
        k3s-master02:
          ansible_host: 192.168.178.162
        k3s-master03:
          ansible_host: 192.168.178.163
