kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:/RVWaZlgsfdQFH9LpDwd2w==,iv:/4XGJmhn4sPtL5iOIzSpT7HmOVwr7mHcdbVf8aufyTA=,tag:CpZSMrBXG+oaLHw3A+WWrg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:eqADSFAkw66f9v0nQHn0uqEZLTK0qdmERqhUKyTMpB0=,iv:klnw1KYUNvtli8jZqh5H93OApRys5qExru4xCaGqWwk=,tag:57x+k9qkn1UnR6HHFydt6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN3A1b0ZJSmxBUGhSakVs
            bklVZmRLdS9tYzY0U1FyRFJxbVVLVUpyclEwCjkzMFQ0K3hhREJxUE9wRjJqeUUx
            cEFXVDBtVElTSGtBbzFmeHcxM2JoTlkKLS0tIDJtREhTNjF1QW45ajBiZ1NPVk84
            eHhXOGttellNMlhuOUZ1MmlVeWJFY2sKLLXJtEWrkxkFn1W55L2ZRoi+lOnu6WGF
            gnDbeWUY/kKyS/qsvyPXrpuagr6LpABOvTbYYB37fAN911uhcdx4cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T15:48:38Z"
    mac: ENC[AES256_GCM,data:vrE6bVGmKmPayOhZayEfjnIK7zMK0KhgS6+gOIJkjXzRSPO2W4lIa9kMKYHqRNpYMbuhh0cU6A6tsxtQlN71NNevY9EMwOJdnuLSU6WtbfRJao3NQktSzCwWmh5jdWSPYjxgnqRDsNY5xinnoP84XZ2ovkd7TSS0P5qIwG57PQ0=,iv:A/Dho+zKsH8BwkDC895Stw73/3huw3vp0BO2O1ywV5E=,tag:/d+l+YRjA2vCpspGWp5h7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
