kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:XloMkXqI1jLtLOGitpFoZlt/yVLwQ7b9Gw==,iv:GzKqnRxhByKV8Hh/phBrjWtncMCKcToZoYWPNCssqz4=,tag:k/qqYCqBxK7SIKyLAdwj4A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:JNUTtj0Lk15X5QxZ5RqFf7lR6jtXS9Z1cD9jmcFCcQ==,iv:Dx1YY10PNcqqmGCGpmIEwhrXwi4pUAwfAfIhjwHEByI=,tag:NdbwRBOV7mt/uW7QjL8uuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN3A1b0ZJSmxBUGhSakVs
            bklVZmRLdS9tYzY0U1FyRFJxbVVLVUpyclEwCjkzMFQ0K3hhREJxUE9wRjJqeUUx
            cEFXVDBtVElTSGtBbzFmeHcxM2JoTlkKLS0tIDJtREhTNjF1QW45ajBiZ1NPVk84
            eHhXOGttellNMlhuOUZ1MmlVeWJFY2sKLLXJtEWrkxkFn1W55L2ZRoi+lOnu6WGF
            gnDbeWUY/kKyS/qsvyPXrpuagr6LpABOvTbYYB37fAN911uhcdx4cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T17:06:23Z"
    mac: ENC[AES256_GCM,data:5El2RuCa+bm/dpG7IAVHzJMG3ZezYAW5X2Tgny+q7v7L7YKRj9+47jFF6247F9xjCmAl5SSxAzFlAl/T9a9EkxWke38FFHC7BchxLX64tILEhzP6JU14DyTO9pp4Hm/mCJheqtKv0L71VhMshrBDnVbyCONU1S9iVDCZ9B9mnx4=,iv:YzAjjfhJlzXOhIE/uK2TGYoFph6cl3rAsR5awLKapMs=,tag:i+JHvDNR8Ct0DGK/rUZ+fQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
