kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-backblaze
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    BACKBLAZE_ACCESS_KEY: ENC[AES256_GCM,data:uOZHK1gLD4YpjL2qh6s/AelsopKqp8pyaQ==,iv:E/vpdaZ/8wpY1hx0U5oZZR7K5Yw8Am8cMgJnmvIxJeQ=,tag:JPZq+hCFoOT/gAonrU794w==,type:str]
    BACKBLAZE_SECRET_KEY: ENC[AES256_GCM,data:24gcGBvveLKsFlWlpM7/zjn46Zfc9fVdd7Bnx+QmWg==,iv:X+4qSrIN4HNs0+RplxMWbCBO085NGNTXk+ZSYdRPau0=,tag:jXI8VnV51reKqKbwGjCfeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN3A1b0ZJSmxBUGhSakVs
            bklVZmRLdS9tYzY0U1FyRFJxbVVLVUpyclEwCjkzMFQ0K3hhREJxUE9wRjJqeUUx
            cEFXVDBtVElTSGtBbzFmeHcxM2JoTlkKLS0tIDJtREhTNjF1QW45ajBiZ1NPVk84
            eHhXOGttellNMlhuOUZ1MmlVeWJFY2sKLLXJtEWrkxkFn1W55L2ZRoi+lOnu6WGF
            gnDbeWUY/kKyS/qsvyPXrpuagr6LpABOvTbYYB37fAN911uhcdx4cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T15:29:54Z"
    mac: ENC[AES256_GCM,data:z/IO0JHRWZXkTay7Af93EMX1Jd6rGvebkjSXx80mK1dwH+Uvrmwwl8Hd5l3y8LVlNnh/fCMTiPkimta6V7ND4MhpyjnBlTwIOyNt8mmllR2QDHFMzUZtFyqK8l+JLqon4IXKKwk3X4lRmuRJCxLMjZhotuQgOSq2xpo/w+Bagl8=,iv:rMOjXUYUZPrYJa72Xlf804zKAx46FHf8sxkMXbh2uZU=,tag:PRP65BlozSOlbAXG3aGQuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
