---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      existingClaim: minio-nfs

    replicas: 3

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.home.arpa/enabled: "true"
        hajimari.io/icon: mdi:pail
      hostname: &api-host "s3.${SECRET_DOMAIN}"
      path: /
      pathType: Prefix
      tls: true
      extraTls:
        - hosts:
            - *api-host

    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.home.arpa/enabled: "true"
        hajimari.io/icon: mdi:pail
      hostname: &console-host "minio.${SECRET_DOMAIN}"
      path: /
      pathType: Prefix
      tls: true
      extraTls:
        - hosts:
            - *console-host

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi

  valuesFrom:
    - targetPath: rootUser
      kind: Secret
      name: minio-secret
      valuesKey: MINIO_ROOT_USER
    - targetPath: rootPassword
      kind: Secret
      name: minio-secret
      valuesKey: MINIO_ROOT_PASSWORD
