---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: minio-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.178.241
    path: /mnt/p/k8s/minio
  mountOptions: ["nfsvers=4", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 20Gi
