apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: default
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:JZiknP6ORA==,iv:qMHkbBO1AbBDtodW6nFWWBuHDfvdcGf+ryfgzfAwES4=,tag:kwX3J8p98aPkTvD2/KGQVQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:FVfqd3tVeV/0,iv:VJWFY53UFcQ3Mh8YAxVKYBgNYvtoCIkoG4bknCrW4oY=,tag:Y9n9M8EqkZLrXLSIj1509A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBramxHZTVoY2FqSkk2RTJh
            QmFJSzlhSW1lakwyWTBjdWRScndNNm5CaVFjCkhYall6TFR4S1NVcnFFQlEyZHRI
            SnI1QnYvcG5zY09GMnp3NWRvMmFhUkkKLS0tIGdwOHNoNW1wc2xkVmExRWJRaE9M
            Mk1GVm5wNGNSUUpWV3JzZ3JzN2xOM1kK35XUNI0tdS7zSWHTNTQwaiFcq/rWT2P1
            d74Z/SA0IhK9cpdhSJ2FTMTSd2svfTzvXNtmCk5kq3qMxHqEqAjQ5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T13:28:06Z"
    mac: ENC[AES256_GCM,data:vnW+yapSccQQudqomdUdaUpdQ8yfpFHLQtnXZXQhmWiQoaEd8RNBsw7D0LE22q9Sb3s0fpOeIkQbFYQG/V4pDx+zAR+uyCR6Eiov/g6qJ+4y0nGHxsxCPFauC5YNWi6si+fSsbeVdu6P+XTxuaG7qOZo+4w5WFzjjz0uVLwoGM8=,iv:LRgJSG66a8/CI/QrZzw7iw07Jjo8be94WF56TkxztVE=,tag:7I+RAEAD6dxQ4+jpsAR9TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: default
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:JZiknP6ORA==,iv:qMHkbBO1AbBDtodW6nFWWBuHDfvdcGf+ryfgzfAwES4=,tag:kwX3J8p98aPkTvD2/KGQVQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:9q/kCO3koBYXv9w=,iv:z4cBs7LiqeLyW/dxu00KjT/CzJiP3b/0PpQALosU7vk=,tag:51h7MAAL83bSpiE4Bkjo9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBramxHZTVoY2FqSkk2RTJh
            QmFJSzlhSW1lakwyWTBjdWRScndNNm5CaVFjCkhYall6TFR4S1NVcnFFQlEyZHRI
            SnI1QnYvcG5zY09GMnp3NWRvMmFhUkkKLS0tIGdwOHNoNW1wc2xkVmExRWJRaE9M
            Mk1GVm5wNGNSUUpWV3JzZ3JzN2xOM1kK35XUNI0tdS7zSWHTNTQwaiFcq/rWT2P1
            d74Z/SA0IhK9cpdhSJ2FTMTSd2svfTzvXNtmCk5kq3qMxHqEqAjQ5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T13:28:06Z"
    mac: ENC[AES256_GCM,data:vnW+yapSccQQudqomdUdaUpdQ8yfpFHLQtnXZXQhmWiQoaEd8RNBsw7D0LE22q9Sb3s0fpOeIkQbFYQG/V4pDx+zAR+uyCR6Eiov/g6qJ+4y0nGHxsxCPFauC5YNWi6si+fSsbeVdu6P+XTxuaG7qOZo+4w5WFzjjz0uVLwoGM8=,iv:LRgJSG66a8/CI/QrZzw7iw07Jjo8be94WF56TkxztVE=,tag:7I+RAEAD6dxQ4+jpsAR9TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-prometheus
    namespace: default
stringData:
    token: ENC[AES256_GCM,data:3PCH3CU=,iv:1Pr5Qxtbiy7G9Abbfe+XmLFd1s13SpCzP0J64f9Xu2w=,tag:Vx+fXw86eHcnDd0XHoWSuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBramxHZTVoY2FqSkk2RTJh
            QmFJSzlhSW1lakwyWTBjdWRScndNNm5CaVFjCkhYall6TFR4S1NVcnFFQlEyZHRI
            SnI1QnYvcG5zY09GMnp3NWRvMmFhUkkKLS0tIGdwOHNoNW1wc2xkVmExRWJRaE9M
            Mk1GVm5wNGNSUUpWV3JzZ3JzN2xOM1kK35XUNI0tdS7zSWHTNTQwaiFcq/rWT2P1
            d74Z/SA0IhK9cpdhSJ2FTMTSd2svfTzvXNtmCk5kq3qMxHqEqAjQ5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T13:28:06Z"
    mac: ENC[AES256_GCM,data:vnW+yapSccQQudqomdUdaUpdQ8yfpFHLQtnXZXQhmWiQoaEd8RNBsw7D0LE22q9Sb3s0fpOeIkQbFYQG/V4pDx+zAR+uyCR6Eiov/g6qJ+4y0nGHxsxCPFauC5YNWi6si+fSsbeVdu6P+XTxuaG7qOZo+4w5WFzjjz0uVLwoGM8=,iv:LRgJSG66a8/CI/QrZzw7iw07Jjo8be94WF56TkxztVE=,tag:7I+RAEAD6dxQ4+jpsAR9TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
