apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:wJ9oURtM27Ww9b9iCmVeyHbA9rYF9ajPcQpcc5XPRQM1Pyr09gtS6g==,iv:22WsQcjA4ILqNfE3x+8tVZSXXkZHswkam/MaqDmIeZE=,tag:E7PMjXdO2l+q9EMYSfk4Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqnf07rzxt8jkwzqyx84t4ag9az3n35hw4m298v6s56d5mf509lqrpcflj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdXdxT2NHUHZQT3RzNVp5
            ZkNsYStFSWY0OVl1UXkwR2JwLy8xSDY0ZVI4CmVZTkpNZ1did2xSaE5GQWJTcnJt
            eng1WHVJaldEQ2hyZEY3QzE4ZXhIcncKLS0tIEV5NEN0d0s4QTRpSHZpTExGM1Zp
            M3NUV0ZhR0dnTGlRS1Y1cFBpdzJTMmcK0V5h8+YIWyxhyAGMjhpTr6ibYXKXt19Z
            eTNVgI7nmqOYUbBQ2p0VoNMVXv7F3sqJWOxpQij/TTLJbBkWlBKGng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T20:33:58Z"
    mac: ENC[AES256_GCM,data:ackee3bLmn3ZbqJJGoy2aJeSPOHyFzKLEaL9LAghJiNKVCLq8F1aYP8JJ2Zp3vwUhHaF1O988n+skMwNTxG6ENucQmYFr9lrbNAT8u0jT64x7UilDo+1Kths/6Afd2ad6SEMsJQn6a/bkzSHqjEDLtovjsr0H0OQsr6cmP0LVfo=,iv:E2RaipjuimbruJXa+YdQcaX5PuHcT0vFOR4Qc79l+Xk=,tag:I38PT5jvq1lLcjQ106JHdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
