apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:KtroTFkDBvbttET1tbl5xDbMRrRYUCcyavYxP8JHQN+6g1blHQ==,iv:JNSEcxY4XmpyFt3U1+7o2FPFuCrSSsKW7eXYbejXIEk=,tag:6uRcoBPd1a0B/CYZk52Mdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbnZJVEF1TWMwTkc1YjEv
            RjdmNHJockR1MGdiMm9ZQ1RmY1JMY1pERWs0Cng3anFkeUV2Rjh3d0kyaEUvQmIz
            NHEvY0MzV2tOTXJGdGNiYk9iOWw1Y0kKLS0tIExNdDMvbDM0cWRVdjJUUmc2d002
            OFlEMDRMcnVpOFA4TWcwaFlLZVNrNkkKzyAGgu2ZS5nXqjmXqyGUwrmybSd9xaAz
            rTSSwbFNx20pP5uQHVVKZfrS+W9X1gtU03aKAAQim40pVNbCAXjSEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T12:28:31Z"
    mac: ENC[AES256_GCM,data:yBu8qUYkceqOp7oILw2peZNacFzSD01PuofJNgptMpJvgbjPp1II0Kasy8nCzFCncUi+k/FP1SKJSqWtboGa8Svtf9IIyy3HmH4wXY4K8hxg9i5fwCRhqmHQDMuu/MVQXGFUXbEwR6gN9YBRyYW55CNURLreBq80OfcJU4nZZHg=,iv:iCFed7GATnCM4uUMCTmC75VlMSbpwn7VlnoyPOnPPMI=,tag:XFaBB4zACzHjJ0SNPsAzBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
