apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:zB4eNopU6I0HujK+Ga5+2reb1U/8uM17XI+5uL8D9cvUWSGZFw==,iv:Qm+y9QcCDDFxqnLRUHR7iq7oCZtDOTVIor/GbbuQEWY=,tag:rK/CSEkoDp0dSyYonX5yOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MUpiUzBuai84SnN5V2Mv
            QlNRbjY0eThWaUtmN09rKzJlNGkvNWRRbGgwCjFXWTlYNWVsS2hKdlo0ZG1XODdV
            Tkc4VHBhMG1JUXZrYmZLUmg1ZytBR3cKLS0tIFNkR3dkSFcvby9iSVZBMnpIZzRI
            TzE3OThESW5YY1dEQlAxNDNBVTIvUncK+TwKItEf6Yxwvm5bGhsLDc9bD6RnayOC
            N4eocVWRejrNx6zSuWvaKxQ84CGXnRO3ulY/YHZpPpv9SPd6DXq8uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T09:36:54Z"
    mac: ENC[AES256_GCM,data:kwfirXNeJLM0D0P52a0/tesRiPxsqVvIs4Jm4DAvSZmRJfUsjovYLLHVsYJ1wE1UHX9cv6JOtNFePPgp09NP+kczyOkbweXGcJXz21/ouPSohFAUUK5AZVEvuQg0znbuAbH2V/Lq5xNGPKgRibhc77jtNJL+eOOF/oSw3I2ZZt4=,iv:lbmvhjk+lndMT0mMI5O5wf2kcwWPmVV/7Nz+IRujNDw=,tag:LTUHixSxda4cEMbfTHGydw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
