apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:AJCz0TAlShThMXH7UwkManYWRsPEDTBWYEdBHSDiKec2k6JnAg==,iv:hY46kp2dDG/PlEwdKG6tUJTv1RLTR09/xZGA8WX9Fio=,tag:X5cRM4lXxjCRVfHsi8Dc8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSHZhVURYRmpZQTNkLzhv
            RHpqTlhQbG9HSkdGYXZlaFlmL3VWenlZd1VjCmdxWTZ6emJkcmhrTGhZSWYwdkhK
            ZnpjRWgzVm1WQ21oVzgyUzRLTGJta00KLS0tIHpMTm5hYTlFcWVUNk4vbUd1U0F1
            WW9Va1NRY3hiZVBGeUR6WENSSWpnNncKD8e0S7qaqPIMET0gn2GsuwfcSPjTqLcY
            mCk1wZKFxtzr0XXIoFmScJXP8zdiDbHg1gxxG4tc3RMhUE2wDbb0QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:01:41Z"
    mac: ENC[AES256_GCM,data:mHvfEZ0gFOXqd9yCsQftIPOZabIvobsHAMsygGC4EOdWB/p7irU7KhSIKcweLRfNQdcWn8Mn6yrSb0XhaPNhBCiIRJ4OKQo+eIeEZ3phe5iIWNQGxq6NJeKdVBWBdAdm2141AP83ajqztx1PkWwH6mh6nw2tbafUiyfktp3LD+k=,iv:KSTopsp3/tBlgBn1CFUnWTu/RQiDh1y7B1DGU4cG9f4=,tag:jIIIV+ivkrOWw4fPr91VGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
