kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: smtp-relay-secret
    namespace: default
stringData:
    SMTP_PASSWORD: ENC[AES256_GCM,data:5B6xZpHOM2XjJr8FuT4=,iv:kmOFloV2TWCCc6fUPGvpaCw8E44i7dBL/rvSLdwz/To=,tag:kGxw4ZJv9MZry9q4Hwh8WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeWpWZmhHUHNzM1pnK2RD
            dXZDQVJrL2xOSkFnVHNWclVTdks2QnNFcVNrCnlrL1lHZWhIREJEUkt4c1NKdDlz
            bXh6b2VnWi8vejFwZnBVWHFpejZOR1EKLS0tIExYc1RranozcTJycXI5SGZabGRS
            YXo3Z2s2bzJ2NE5CeDN4Rk51VkNyK2cK0sDDeRyoKUkNL+t9xyP/4u0OLJvrijuk
            AmNA6mlNNAwgvyAvadO+2cNEFMG80OFXU9zlv2zX/gNLyAMOkWzJhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T11:33:53Z"
    mac: ENC[AES256_GCM,data:nACIagwVSZbzPhRvVSm5Pa59DTeChsNOC4qJIfkm9tQ0HvxcrURw1EM8lBCg2LtQGznI0QV0SznT/caWeUWTmztfYY3S9h2ZueSkjyWHnlEbproAAOgExP8sCPbktAta3X9PE/fbhQgOxmjkXpAh5m9/XH3ujcGsTtuGhTGU2vo=,iv:hWyDL/gWEt95RYdEZstC1RSFaSpn69N30pi9y3oVgFY=,tag:PqzVN/d/CQckl7XMMkFnZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
