apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Fb4V8MO1qs8cXtj1fYbbasKD,iv:FVaws3oKoLiFKC2dXGu4v+0vDqBz1jwIyFG+pCWkmTs=,tag:61MWD3glnN5lR5ALRgS4Rg==,type:str]
    api-key: ENC[AES256_GCM,data:o80i0oUQg0hgZpv1tZxqPn0Kr1FAnTwX07xm8wZu3L21jf/MPw==,iv:nZKEc3kN4ptFaHVRCcRmvsLh77dfuS0AHQmUeVhJJtU=,tag:A+bv9ug49FFgidCY5FLdzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQVdYSEcxSWRIcGlzclBq
            cGxsVGRGZDNuQzN2OU5oUlFoNXFmM1VoU0EwCnJBMVMwTFNjeUprNlE0SDVVVWpF
            ZW1hS0JnTjVzQnF6bzZTaFdNUis0cmMKLS0tIG80MnBvMnczeGZtdTAxRlpTamow
            ZHFZdjZVaWNWYlpqbURoUncwb1lqR3cKD57XgyOr0Se2yP0uoUQqf/sLLTO6kvqG
            QHkc8RdWXBl3urSr1St6Z87rcmGMCp3padSYSXsrKrdycY7u+TB2ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T12:28:31Z"
    mac: ENC[AES256_GCM,data:oOAULR1OBKljYfGfL3WHNLIZFHCcb3xQYGFRyutbNbQxvVL1YCepcgb/uEDFMxMAJPahgovPgD53c/43Uld4+WWINJDsEET5nI7iNQG9scnipskkRV4gjsZUmlorVjQ+w5ZmbmISBq3v019Bj9jVceQoD9yTeQxFNKfJaQZ9GzI=,iv:/Z57Plmn996EbiI8WhMGeR992SxP36opH0Nk3NXUXU8=,tag:+TGbyjVuNnPJb5bofaHPRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
