apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:pg+OoSeV5y94411gxgVX6leG,iv:tNPcgy7wBahISPmUKXLLQrtyd+Mz/jTd7U/i0WWIZg4=,tag:AJ4EbBAFctVg5FVWG9YBHA==,type:str]
    api-key: ENC[AES256_GCM,data:J2JoYBVsjTnZDM93Uz5G+3Lz3SHfRm7a35dqZso2Nc/JNEKZcg==,iv:MCXQJ37p89NWpqvOJ/Nudbs3tdT2cDmb8EmWN+h3Goc=,tag:ofBvd0gRZ5UPBcdXAapz8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMC9NRzVxRmFveFdGUSts
            T3NoRElXbEVDaUg2OVp3NDh6NDNLbVdCTW5jCllJSCtRNzBNQTNvQXJMK05kd0M4
            MVFNTFJWSUFoazZhMG05N2NpR1gvUGsKLS0tIFlsMXJCRVNjWVZvNENBOVlCUDhU
            VHBtejVYSVpKcGVyRWFBK0dSTG9jMWcKHLHIu90TddyN6INpso9N9xT8uk5RmIUm
            U3idjf9d574wEYm7RBBOBDXGMV2TGmX5PpFsKL8NU/fYlFTJvI0Phw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:01:41Z"
    mac: ENC[AES256_GCM,data:a2sBMs+96lhXHVfh/gFp4LpuMQCLlji0GdcuuVz4nAeaesP63U1BTNzJnf+OghtPelFKVG9JyPP3ZOrAdZDOqHfzO8hAYqYCcsv6LIj2Xrvi4bu9r46SPST2t9BKStLewmiyBDZXBOJvsL9VB+t29WWKyFeHCaWwqfYcqAdyHr4=,iv:FR+t51eb0bSFXp2Hs+wOo3Cra2RKfWOi4cMz0oLxP6I=,tag:j3pbXEqueSBVQ/4woc0kBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
