apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:5dgAYMmgjBFGKoQ5CmMQ4kd9,iv:HCvZd+PZWo4D8HGR4tWuR/tSKE5yLta8GDdMyZ3OQ9Q=,tag:cyGcvsssTEjFE0bcstvhkQ==,type:str]
    api-key: ENC[AES256_GCM,data:/QvEtGdQUl5RAmpbLl+noj1Hd7zGBvYU1ucEn/pT7SDwNhp8Fw==,iv:Ig/OwRzHGekTTIftLSNNa54EQ31LkuKQYZl5RhC8JPo=,tag:ovRr20w3B4tmvGdz4h3KaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNakZ2cnZpQm5kakJ0QnZU
            MW9lTkhKWjRWUDBmWnJTZ3hjZUZVV2dLUTAwClladXZtbS9kcGgwSDZXQU9vcC9I
            VnFDRlpyaGNYM05aM3FWQkZjcENmSHMKLS0tIHFXREpoSXYvOWE2aTRsRDlIS3Vu
            K0hBZ212b0hURmZ0MlFPWW51SElad0UKO55lUa84ZvX+s5kZk7yGffvrkJV0Gfar
            mmLVNjp6xj2a5NtShB8GTAbGeoaU4Tm+nyPyH/21qUccS5p2zuH0JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T09:36:54Z"
    mac: ENC[AES256_GCM,data:hcWdF+RNo3wTKcsWOPkCkxx4xQiZqMi7mAlwSbnhjKatM2pzirXkr005wnXzQZFt4aCHPHobF+NcJKigcptX75lyNBQ2uBALhzzxGUr1mLUpuYeKxU3HM0iLT8T+5+IcCUWh6JfZNBq+8eTLH/hcdu8daDiO9VYM+XhxQevrPXk=,iv:ObWZsq3UGlqc0MjMumBQF05UcAhZineTH1B2DmoMj78=,tag:r++b+ke0yC+wk6RKBePJZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
