---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./hajimari/ks.yaml
  - ./discord-template-notifier/ks.yaml
  - ./mosquitto/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./home-assistant/ks.yaml
  - ./node-red/ks.yaml
  - ./shlink/ks.yaml
  - ./kubernetes-schemas/ks.yaml
  # - ./lldap/ks.yaml
