apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:oy9GkM7GjgkG73GzQuGTpIgQkgv29jeVIlF09XJLYUu5rC0tKMbCKU1w+aZI2jcFG9+9xJ4Ga+Gq9CvZ,iv:Tg2fIL3ra+965KI3krJpbykapYTuMNbOQPGoVp9C4GU=,tag:bEiVGyBr4BDoxiY6RHz8Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L0NTandwSzd5blRsZk9n
            OWZGcGY1d3NsYlB1Y1MvWFJ0aDhwM2JPVWpFCmRKa3A1OEFyeFZxSTM0RlNKTzNx
            UjRuOE9QY2h6bWVrQm8yZGNwQXE4a2cKLS0tIEIrVVF5eTlMUmxjRE51aHRDU2FK
            L01pNExKNEx6d0tCRUl3NHJRcDRsQXcKjax5WwB/fWY+IcaJyWG4JRtVS8YQf0UZ
            xY7jZ/QUqUIGiEoQIlEcCSMRViychsR0kk0f/7GYhKOc85Tfzr1fpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T12:28:34Z"
    mac: ENC[AES256_GCM,data:R2H2QqHV7wkNy2JIWM4cWDL4COU+uxSrvtFtXRqbWmzNlsgLEvlroBb3amKC4OU8u0G1IHSuLhl+hD9dL/v5atDcYJAKiKiOGCEw8wwReq4f9ccc9N8Ili4AxLiFN9BEq8XmkWZfIR8m+cb8JZBceLFE4KnN+3dg6QRdqmW4t2E=,iv:nbh+L1K46f36lMa+xbpZhjncH2HFHBvqLgr/aIOP+pE=,tag:01v09arQkTR0GpVBXS5GSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
