apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:HG5EYUf5yY0bLIBJHrioYYRywZxnK5Z1wO1mVSWtv9+Gqta3bREoihbxO5Pa5yfFCknIVsvNo14y9H+K,iv:qNFJ4VxqbCrj5xVt59j7v57XMSjNilrUnJWpTlfJHxk=,tag:o10QceLjpotkfl0KT/HFLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZWQ5ZXRBQU1xMm1BUkE4
            KzNaMDlRTm8venVIMzRsSnBBMHNSeHlGYjN3CjFBZk9YQVBUamxsZGpIR0YrZWUx
            WHVaanV0bUE3dlFJakgwc29QU2NkZ00KLS0tIG5RaHZCbDNlWkx3cW9DVmNpdTht
            UzR3Ykd6dzdrMGRtaDB3WHFZRzJWWFkKUxz5Ujl8vU+uinQNk9lXXUBx7L2AV7+8
            3H1ZqFX4sIHA0xU8pz7yvnthII51qqiWC0mKVtQx5imEB8mcAxSgLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:01:43Z"
    mac: ENC[AES256_GCM,data:qqNIP1HPU53z8cs8YjztmMAWQWaRkJlJ6n2Ne/O9vjKDopFU9jLa4bGNtaa4lBwrAnHcDQx3jKotWNzT+gYQaSCQwy2gler6+bjp+jpEYraIy22/ipxVbNnrDp0+AtxIghJThyrSfZcQ25NN1rhsIRZLll3hQnqZbGJ+jt4h/wQ=,iv:/8IHeyWL6WKxR+fyIUjt0iSeUgiNPiibl/sanESLwE8=,tag:4xj9Qd6YgVQF+zO5rqY+MA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
