apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:hiFSZkuyJcFU8uGoD2hklb9lZfMXRtcdtbAw6omRLcSG0AgPXHkfh6Le7M4u9z54GUF0eH6SSUdZmULF,iv:64QkaRqs10F6RepVL3fVstxzt0+KHyy1ft9eJzCPq/8=,tag:uNMWVSmV7ZaFIqmXB8B7aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZG5ocmZNMElOUyt0bUFS
            dXJPL0N2T3lkQnNjVVMrUWk1aDM1M1VGbHl3Ck1qc202c24rRUxwSXlxRFpvZDBx
            Rmo4ZHNOSGE2MTlmdEJ1bHZDalV1WncKLS0tIE1ldGhGNHRmRGhDVyt0b2FmQnpy
            ZXFJaXIrNHhJN2lpNUFLdERCVHJPZ2cKU7jywc3qwGbqs7ICRERPvuUMSQ5R1BSg
            HFm07/g6/cdJYHC701RV2nTmdGkE1I5BhfJjTbT5YpHTr96JR7s+RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T09:36:56Z"
    mac: ENC[AES256_GCM,data:pa67febE2YHCEOGOTYqMucWFXSXzyAWygn5PyCTw0w5+J6/ri1zuBP22TiPWoHx69EbC8HNWXHCtXplj3H0B2/iUfion7buTLsgkOfMlkxlrbTLZLNmvTjCgaeyGyGtUK2DLXzVcnVPlj+rivTm9zaHFxEtZeMmtclEBjpAjC0U=,iv:E5tGAo8+kIazeRcQfgTqM+qBAu7xyGQNrVWnZzxvhNg=,tag:C8Ncmhfp7c74RBIis0/slA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
