apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:CFMgnVCvQA8Sz3UQIG17I2r0,iv:Qab7jU4pTnFqk806lF1JeDFTKsnb4cgftVJQ3OEi23U=,tag:yfxFQ9ZDOV7lgYBmo+1PQg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Yt6FTsDCJC0R9CAXDl4dK2hbZY+rRHN4kzreyI4KEFub/9F8,iv:poVjRGZY+1/p6eRoVzeEmQRdH3gcj3NsWxqfgxZJxn4=,tag:Sb3a2atA30zzjjUQfY6J/g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1OlG/Hd8rjVisQ==,iv:gfCs1yqM/0MrT6f+YjrqPHLGZN5h71YXZ1QSWdcw53g=,tag:wN41bdgjoVjkv/Qe87ndig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqnf07rzxt8jkwzqyx84t4ag9az3n35hw4m298v6s56d5mf509lqrpcflj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MWVxcGJDSFdtaGxTajhO
            SUp5QzhKcG00U0FVTUF0dG11cHlQZ211S1dVCkJLeWJ0NFp4dEFSRS9Bc09uNHUw
            ZUtJOEtDMmNHNkZ6V1gwNUszbTd6aGMKLS0tIDF2cy9SUjZsa3NiS3Jqa2ptTktT
            YmEyT1puSDd2SzlJR2diOUFXaHRzNlUKhx7pX31QJQ6eAt/nhBwE7MMs/yweQfNF
            LFkD+9hXA4dWHcs+o3DoTECSlmu6VGI8zKPBg7sjoerMgAyQlDQlUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T20:33:57Z"
    mac: ENC[AES256_GCM,data:lWaiIQhNSW3Nqw3cplu1uiIzrxEuGLTuAZq+62jV5pMf78MJfGV6hcA9+fHZBqd0T5QjjEAyZ3m9r+09VbOs2egHLlgSj5lnsicaXmFspgLjE2rc4t3JPTQADnB15Sv5QjzOVwcCFRp6m5OLbRjpipMpafNb47n9EhWNekvtf5w=,iv:OFoqYPFiAIgeov1UliXddcOFOojLl2Mj095Y7EzwIvU=,tag:JsMnhMRYm1v1gTWwKyObiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
