apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9NU/YOnl1p/YRw==,iv:swrQtNH6/39OxBZPVlmgddq0zZHrUbr1pYcmxFPSdTQ=,tag:jwNk8R51JPw0hX+406tr+w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rEoF91uF0fpJSUqlD11NhbEW,iv:uxFxTv3LcAC7tb0AtWS+DTBxG/NMxV9VXMfY9lkIAhE=,tag:TteySAPmx3icU+UDTNvJ0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMWZFZFNSSmRqRnNxQ21P
            Y3l5NFdOTVQzRmNKWnJYZEMzd1U2Y0J2UG04Cng4Z2lvUURCY3A1d1BxRXhRak9R
            MVo2cWFrL3BBWklwSTJMcWhpYzlsMEEKLS0tIEltRUE4N0ZmanhPdko5ZGx5UGhi
            N3IrVXNxUksreFhaMkpTcThIQnBiNmsK7F5/rn8JRH7zi+dIx7TAe/dq1gmqpGSJ
            B37zw6p7cSssqBGDidqVnUhv6PbSYFpCAAOZUlUqE23wGfLARrkBsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:01:41Z"
    mac: ENC[AES256_GCM,data:y8pNi1oE+ajyVZzfcEcUclMfGen23oUsyWW3dXHYrkl9MMF9LXoZTIWRubPvzTEKyXgyDeFI4pb7T/N4LAfwCRwnohZCO99M2waPP5XD0WvOyI1QPCc/p+J+kyezXVugBgD5BFCzVxDnLGJhRDPUH6B3aVaA13/Bfh/bRaOePwI=,iv:c3G9TWYManDz472SnHwRS09r4c18NO7TzKNOXiC9WSY=,tag:RqgpCxL7Pj1rsv2pmvvihg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
