apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:otVeP9pCGqICIw==,iv:wCETl1TFmecFEqh6Zl5r7cnwS45solfEfFg8xEr5KEQ=,tag:U3fGXCJ+Nj7nK8MM6H1tkw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JVT4/0YA/nVrtLweEAunqCTd,iv:xxnoadmy8E7YkI4cweykES4a8YzEYF8NlUK64+PA/tc=,tag:MKU7vEQWgbxPv5IsGuXPcg==,type:str]
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:78TdMVqkN8sHKv4=,iv:WrFWrWo+dzky+3BH2HS4ULO7bQ9OrtDo9HexJ28etXc=,tag:X0CXmLpPr2Flt/uvW/wDog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeUNXd2Q4V0lJdjBPZFZP
            QUFPcEhxUmcvQWpvb3hibnJnMWxhUnZYVlZBCllRYlRUOWJwQzNPMkh1b00zT2Nz
            UzdEWlM1bGJWdGtkSExVZWFUcjdQZ2cKLS0tIG94RGRmQTVsMU82b21UUzBXbENs
            WWNtdDUweVpIV0ZFZGJxQkd3azNQWTAK6gijKVEdczJvrjzrK6fiCKovduFp4p9b
            R8E3Ig5uKdKpVw262bpbic6dYk+J+zh6RYhnqAmhAHM4Wv3uugY+Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T17:38:16Z"
    mac: ENC[AES256_GCM,data:Om2qCQbDds1C8hkjJUkm9A61UzSX7LeC7PXQBbywC6iIBSjllYK9dwY9YKclPDmBTEFkCnwDYR11U3wD+g364zCDNUXUEFyZ1iqZKgbAtqAnYf4SHu2pTBDJcQC+Awl28U7CJg4D3Uo53Xx5Yq2osfEg2sFqHsYGZdQWZfzDJ7I=,iv:wJpt5SXFAIikXziHxzpFzgKmaq/abuIQPyCPzwFHpUc=,tag:ZzxduJ/oEkPImNZ1WPhRPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
