apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:otVeP9pCGqICIw==,iv:wCETl1TFmecFEqh6Zl5r7cnwS45solfEfFg8xEr5KEQ=,tag:U3fGXCJ+Nj7nK8MM6H1tkw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JVT4/0YA/nVrtLweEAunqCTd,iv:xxnoadmy8E7YkI4cweykES4a8YzEYF8NlUK64+PA/tc=,tag:MKU7vEQWgbxPv5IsGuXPcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeUNXd2Q4V0lJdjBPZFZP
            QUFPcEhxUmcvQWpvb3hibnJnMWxhUnZYVlZBCllRYlRUOWJwQzNPMkh1b00zT2Nz
            UzdEWlM1bGJWdGtkSExVZWFUcjdQZ2cKLS0tIG94RGRmQTVsMU82b21UUzBXbENs
            WWNtdDUweVpIV0ZFZGJxQkd3azNQWTAK6gijKVEdczJvrjzrK6fiCKovduFp4p9b
            R8E3Ig5uKdKpVw262bpbic6dYk+J+zh6RYhnqAmhAHM4Wv3uugY+Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T12:28:31Z"
    mac: ENC[AES256_GCM,data:31Cz0XWDISDYxnvALiNv7X/NR9qu+cqZQJu6LmduA351oFtZKRVBGFVUmWq4V5tCmnFYIUkPISYXGHB9ZOui5LvKQcwTN5kQcth24Z/lCW5eVxz3hb97CAz2A1dl5uNxxa5mxow21V9GfJKDxlVySnNZHvErqxFLHIjzuin5xHg=,iv:cFwH+TPUl4QV8nFuNRDdu7/wxufWui+SE8JlEop5Pz0=,tag:hXofvTMA8+m73PEL6nkJOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
