---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slskd
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slskd
spec:
  storageClassName: slskd
  capacity:
    storage: 1Mi # Size does not matter ...twss
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${TRUENAS_STORAGE_IP}
    path: /mnt/s/Apps/Soulseek
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: slskd
  resources:
    requests:
      storage: 1Mi # Size does not matter ...twss
