---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets-stores-onepassword-connect
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets
    - name: cluster-apps-nginx-external
  path: ./kubernetes/apps/external-secrets/stores/onepassword-connect/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: onepassword-connect
      namespace: external-secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m
