---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-democratic-csi-truenas-iscsi
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-snapshot-controller
  path: ./kubernetes/apps/kube-system/democratic-csi/truenas-iscsi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: truenas-iscsi
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: cluster-apps-democratic-csi-truenas-nfs
#   namespace: flux-system
#   labels:
#     substitution.flux.home.arpa/enabled: "true"
# spec:
#   dependsOn:
#     - name: cluster-apps-external-secrets-stores
#     - name: cluster-apps-snapshot-controller
#   path: ./kubernetes/apps/kube-system/democratic-csi/truenas-nfs
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   healthChecks:
#     - apiVersion: helm.toolkit.fluxcd.io/v2beta1
#       kind: HelmRelease
#       name: truenas-nfs
#       namespace: kube-system
#   interval: 30m
#   retryInterval: 1m
#   timeout: 3m
