apiVersion: v1
kind: Secret
metadata:
    name: redis
    namespace: default
stringData:
    redis-password: ENC[AES256_GCM,data:eJB5M2l1oQLG,iv:ysb9o2c3oeq7kq8XV+L9WohPzwsazKXoUTw7G2jUxzQ=,tag:b4EFpqQUB5yTM1YPqj6kug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZFU4ejNDQkk4VlFSakdn
            by8rQjZ5TzIzTmthN212dXZvVWV3L21CSFhRClRIcVlnbzBpSUdvaERPSitIK1E0
            SFJiOXIyRzhxekZwd1VLSDd5bXVMUWsKLS0tIDE4QnF6eHFxOFcyVVdiTmgva0Jn
            T1BFVjAwMmY3YmNQQ3dTOFh1b2pxQzAK93R/wfVryMDr1iZ8kLMl4K68tm47kBP1
            gYahBvk9DiTpnvaBMbcXZFfknlRoceckpz9PTRo4SK6w2qdKF7982w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T11:06:58Z"
    mac: ENC[AES256_GCM,data:l4twB0DYZJRlL3qdsI3AbtsJsLYiD3NvPSIra9uD9ZSVIhkvapp72gq7n7OrVn5OVjDS5b+OVVW3u9MNSwfGrdc1lq3wPgrBF5czazePKGh/YmlmgCQoyM2zH2gNpkifOOUsgvy2m8LsuqpaqhTQpjdMC1fSf6g/mFx+qVybjVE=,iv:ke0cI0h8QholEPdFBhKCUnz9sd6ECLCUk29THwDrifY=,tag:CmlqKsJHzHKKa2UtWQG1zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
